theme: jekyll-theme-minimal
title: BookMark-It
description: Showcase Entry Submission 1 for Final Year Project 2024. This webpage will include details outlining my project including acedemic and commercial titles , project description, links to my poster, demo video, and GitHub Repo of my project BookMark-It.
background_color: "#F3E8D8"